### PR TITLE
feat(datacatalog): Deploy Thrift Server, Hue, Ceph into a single namespace

### PR DESCRIPTION
**Pull request by tumido**
Resolves: #15

Requires: https://github.com/opendatahub-io/odh-manifests/pull/227, https://github.com/opendatahub-io/odh-manifests/pull/228, https://github.com/opendatahub-io/odh-manifests/pull/250, https://gitlab.com/opendatahub/opendatahub-images/-/merge_requests/4, https://gitlab.com/opendatahub/opendatahub-images/-/merge_requests/5

Deploy full data catalog:
- Hue
- Thrift server
- Minimal spark cluster for Thrift server
- Ceph

It also interconnects:
- Hue -> Thrift Server
- Hue -> Ceph
- Thrift Server -> Spark
- Thrift Server -> Ceph

### CODE REVIEW

**Comment by martinpovolny** [comment]
@tumido : how big cluster do I need to test this? did you debug it on Quicklab or CRC?

**Comment by tumido** [comment]
@martinpovolny yes, Quicklab is totally sufficient. It all requires just about 10 pods + 3 PVCs. :slightly_smiling_face: (The claims are `1GiB`, `1GiB` and `5GiB` though it barely gets used on demo installs) I've also optimized the Hue image size greatly, so that saves you another 1GiB of storage. :slightly_smiling_face:

**Comment by tumido** [comment]
@martinpovolny correction: It requires at least 1master + 2 worker nodes OCP Quicklab cluster. Due to memory per worker restrictions on Quicklab. :slightly_smiling_face:

**Comment by tumido** [comment]
With https://gitlab.com/opendatahub/opendatahub-images/-/merge_requests/5 applied, Hue works even with ceph nano. :slightly_smiling_face:

**Comment by tumido** [comment]
@durandom @HumairAK question: Do we want to include the standalone ceph into our manifests here? I think this should be a thing for CRC/Quicklab but on MOC we should be pointing it to a more robust, persistent ceph store.

This is very much related to https://github.com/operate-first/odh/issues/36

**Review by HumairAK — APPROVED** [review]
lgtm

**Pull request merged**
