### PR TITLE
Add additional JH notebook imagestreams

### PR DESCRIPTION
**Pull request by 4n4nd**
Addresses https://github.com/operate-first/odh-moc-support/issues/2

### CODE REVIEW

**Review by HumairAK — APPROVED** [review]

**Comment by 4n4nd** [comment]
@harshad16 in this PR, the pre-commit hook was run after the PR was merged

**Comment by harshad16** [comment]
@4n4nd  would we like to have a merge when all checks are successful for this repo?

**Comment by 4n4nd** [comment]
> @4n4nd would we like to have a merge when all checks are successful for this repo?

Yes

**Comment by tumido** [comment]
Resolves https://github.com/operate-first/continuous-deployment/issues/30

**Pull request merged**
